package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 3:58:00 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name="Archivo"
    ,catalog="categorizacionbd"
)
public class Archivo  implements java.io.Serializable {


     private Long idarchivo;
     private Docente docente;
     private String nombre;
     private String fullnombre;
     private String tipo;
     private byte[] data;
     private Date fecha;

    public Archivo() {
    }

    public Archivo(Docente docente, String nombre, String fullnombre, String tipo, byte[] data, Date fecha) {
       this.docente = docente;
       this.nombre = nombre;
       this.fullnombre = fullnombre;
       this.tipo = tipo;
       this.data = data;
       this.fecha = fecha;
    }
    
    public Archivo(Long idarchivo, String nombre, String fullnombre, String tipo, byte[] data, Date fecha) {
    	this.idarchivo = idarchivo;
        this.nombre = nombre;
        this.fullnombre = fullnombre;
        this.tipo = tipo;
        this.data = data;
        this.fecha = fecha;
     }
    
    public Archivo(String nombre, String tipo, byte[] data, Date fecha) {
        this.nombre = nombre;
        this.tipo = tipo;
        this.data = data;
        this.fecha = fecha;
     }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idarchivo", unique=true, nullable=false)
    public Long getIdarchivo() {
        return this.idarchivo;
    }
    
    public void setIdarchivo(Long idarchivo) {
        this.idarchivo = idarchivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddocente", nullable=false)
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="fullnombre", nullable=false, length=100)
    public String getFullnombre() {
        return this.fullnombre;
    }
    
    public void setFullnombre(String fullnombre) {
        this.fullnombre = fullnombre;
    }

    
    @Column(name="tipo", nullable=false, length=100)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="data", nullable=false)
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


