package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 10:54:14 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name="Archivo"
    ,catalog="categorizacionbd"
)
public class Archivo  implements java.io.Serializable {


     private long idarchivo;
     private Docente docente;
     private String nombre;
     private byte[] data;
     private Date fecha;

    public Archivo() {
    }

    public Archivo(long idarchivo, Docente docente, String nombre, byte[] data, Date fecha) {
       this.idarchivo = idarchivo;
       this.docente = docente;
       this.nombre = nombre;
       this.data = data;
       this.fecha = fecha;
    }
    
    public Archivo(long idarchivo, String nombre, byte[] data, Date fecha) {
        this.idarchivo = idarchivo;
        this.nombre = nombre;
        this.data = data;
        this.fecha = fecha;
     }
    
     @Id 

    
    @Column(name="idarchivo", unique=true, nullable=false)
    public long getIdarchivo() {
        return this.idarchivo;
    }
    
    public void setIdarchivo(long idarchivo) {
        this.idarchivo = idarchivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddocente", nullable=false)
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="data", nullable=false)
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


