package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CalendarioDetalle generated by hbm2java
 */
@Entity
@Table(name="CalendarioDetalle"
    ,catalog="categorizacionbd"
)
public class CalendarioDetalle  implements java.io.Serializable {


     private long idcalendariodetalle;
     private Long idcalendario;
     private String actividad;
     private String descripcion;

    public CalendarioDetalle() {
    }

	
    public CalendarioDetalle(long idcalendariodetalle, String actividad, String descripcion) {
        this.idcalendariodetalle = idcalendariodetalle;
        this.actividad = actividad;
        this.descripcion = descripcion;
    }
    public CalendarioDetalle(long idcalendariodetalle, Long idcalendario, String actividad, String descripcion) {
       this.idcalendariodetalle = idcalendariodetalle;
       this.idcalendario = idcalendario;
       this.actividad = actividad;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="idcalendariodetalle", unique=true, nullable=false)
    public long getIdcalendariodetalle() {
        return this.idcalendariodetalle;
    }
    
    public void setIdcalendariodetalle(long idcalendariodetalle) {
        this.idcalendariodetalle = idcalendariodetalle;
    }

    
    @Column(name="idcalendario")
    public Long getIdcalendario() {
        return this.idcalendario;
    }
    
    public void setIdcalendario(Long idcalendario) {
        this.idcalendario = idcalendario;
    }

    
    @Column(name="actividad", nullable=false, length=50)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


