package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 10:54:14 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Calendario generated by hbm2java
 */
@Entity
@Table(name="Calendario"
    ,catalog="categorizacionbd"
)
public class Calendario  implements java.io.Serializable {


     private long idcalendario;
     private String proceso;
     private Set<CalendarioDetalle> calendarioDetalles = new HashSet<CalendarioDetalle>(0);

    public Calendario() {
    }

	
    public Calendario(long idcalendario) {
        this.idcalendario = idcalendario;
    }
    public Calendario(long idcalendario, String proceso, Set<CalendarioDetalle> calendarioDetalles) {
       this.idcalendario = idcalendario;
       this.proceso = proceso;
       this.calendarioDetalles = calendarioDetalles;
    }
   
     @Id 

    
    @Column(name="idcalendario", unique=true, nullable=false)
    public long getIdcalendario() {
        return this.idcalendario;
    }
    
    public void setIdcalendario(long idcalendario) {
        this.idcalendario = idcalendario;
    }

    
    @Column(name="proceso", length=50)
    public String getProceso() {
        return this.proceso;
    }
    
    public void setProceso(String proceso) {
        this.proceso = proceso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="calendario")
    public Set<CalendarioDetalle> getCalendarioDetalles() {
        return this.calendarioDetalles;
    }
    
    public void setCalendarioDetalles(Set<CalendarioDetalle> calendarioDetalles) {
        this.calendarioDetalles = calendarioDetalles;
    }




}


