package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 10:54:14 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CalendarioDetalle generated by hbm2java
 */
@Entity
@Table(name="CalendarioDetalle"
    ,catalog="categorizacionbd"
)
public class CalendarioDetalle  implements java.io.Serializable {


     private long idcalendariodetalle;
     private Calendario calendario;
     private String actividad;
     private String descripcion;

    public CalendarioDetalle() {
    }

	
    public CalendarioDetalle(long idcalendariodetalle, String actividad, String descripcion) {
        this.idcalendariodetalle = idcalendariodetalle;
        this.actividad = actividad;
        this.descripcion = descripcion;
    }
    public CalendarioDetalle(long idcalendariodetalle, Calendario calendario, String actividad, String descripcion) {
       this.idcalendariodetalle = idcalendariodetalle;
       this.calendario = calendario;
       this.actividad = actividad;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="idcalendariodetalle", unique=true, nullable=false)
    public long getIdcalendariodetalle() {
        return this.idcalendariodetalle;
    }
    
    public void setIdcalendariodetalle(long idcalendariodetalle) {
        this.idcalendariodetalle = idcalendariodetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcalendario")
    public Calendario getCalendario() {
        return this.calendario;
    }
    
    public void setCalendario(Calendario calendario) {
        this.calendario = calendario;
    }

    
    @Column(name="actividad", nullable=false, length=50)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


