package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 3:58:00 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="Categoria"
    ,catalog="categorizacionbd"
)
public class Categoria  implements java.io.Serializable {


     private long idcategoria;
     private String nombre;
     private Set<Promocion> promocions = new HashSet<Promocion>(0);

    public Categoria() {
    }

	
    public Categoria(long idcategoria, String nombre) {
        this.idcategoria = idcategoria;
        this.nombre = nombre;
    }
    public Categoria(long idcategoria, String nombre, Set<Promocion> promocions) {
       this.idcategoria = idcategoria;
       this.nombre = nombre;
       this.promocions = promocions;
    }
   
     @Id 

    
    @Column(name="idcategoria", unique=true, nullable=false)
    public long getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(long idcategoria) {
        this.idcategoria = idcategoria;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set<Promocion> getPromocions() {
        return this.promocions;
    }
    
    public void setPromocions(Set<Promocion> promocions) {
        this.promocions = promocions;
    }




}


