package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComisionMiembro generated by hbm2java
 */
@Entity
@Table(name="ComisionMiembro"
    ,catalog="categorizacionbd"
)
public class ComisionMiembro  implements java.io.Serializable {


     private long idcomisionmiembro;
     private long iddocente;
     private long idcomision;

    public ComisionMiembro() {
    }

    public ComisionMiembro(long idcomisionmiembro, long iddocente, long idcomision) {
       this.idcomisionmiembro = idcomisionmiembro;
       this.iddocente = iddocente;
       this.idcomision = idcomision;
    }
   
     @Id 

    
    @Column(name="idcomisionmiembro", unique=true, nullable=false)
    public long getIdcomisionmiembro() {
        return this.idcomisionmiembro;
    }
    
    public void setIdcomisionmiembro(long idcomisionmiembro) {
        this.idcomisionmiembro = idcomisionmiembro;
    }

    
    @Column(name="iddocente", nullable=false)
    public long getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(long iddocente) {
        this.iddocente = iddocente;
    }

    
    @Column(name="idcomision", nullable=false)
    public long getIdcomision() {
        return this.idcomision;
    }
    
    public void setIdcomision(long idcomision) {
        this.idcomision = idcomision;
    }




}


