package pe.edu.unsch.entities;
// Generated Jul 21, 2019, 9:48:04 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comision generated by hbm2java
 */
@Entity
@Table(name="Comision"
    ,catalog="categorizacionbd"
)
public class Comision  implements java.io.Serializable {


     private Long idcomision;
     private JefeDepartamento jefeDepartamento;
     private String nombre;
     private String razon;
     private Date fechaCreacion;
     private Set<ComisionMiembro> comisionMiembros = new HashSet<ComisionMiembro>(0);
     private Set<Informe> informes = new HashSet<Informe>(0);

    public Comision() {
    }

	
    public Comision(JefeDepartamento jefeDepartamento, String nombre, String razon, Date fechaCreacion) {
        this.jefeDepartamento = jefeDepartamento;
        this.nombre = nombre;
        this.razon = razon;
        this.fechaCreacion = fechaCreacion;
    }
    public Comision(JefeDepartamento jefeDepartamento, String nombre, String razon, Date fechaCreacion, Set<ComisionMiembro> comisionMiembros, Set<Informe> informes) {
       this.jefeDepartamento = jefeDepartamento;
       this.nombre = nombre;
       this.razon = razon;
       this.fechaCreacion = fechaCreacion;
       this.comisionMiembros = comisionMiembros;
       this.informes = informes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcomision", unique=true, nullable=false)
    public Long getIdcomision() {
        return this.idcomision;
    }
    
    public void setIdcomision(Long idcomision) {
        this.idcomision = idcomision;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idjefedepartamento", nullable=false)
    public JefeDepartamento getJefeDepartamento() {
        return this.jefeDepartamento;
    }
    
    public void setJefeDepartamento(JefeDepartamento jefeDepartamento) {
        this.jefeDepartamento = jefeDepartamento;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="razon", nullable=false, length=50)
    public String getRazon() {
        return this.razon;
    }
    
    public void setRazon(String razon) {
        this.razon = razon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comision")
    public Set<ComisionMiembro> getComisionMiembros() {
        return this.comisionMiembros;
    }
    
    public void setComisionMiembros(Set<ComisionMiembro> comisionMiembros) {
        this.comisionMiembros = comisionMiembros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comision")
    public Set<Informe> getInformes() {
        return this.informes;
    }
    
    public void setInformes(Set<Informe> informes) {
        this.informes = informes;
    }




}


