package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsejoFacultad generated by hbm2java
 */
@Entity
@Table(name="ConsejoFacultad"
    ,catalog="categorizacionbd"
)
public class ConsejoFacultad  implements java.io.Serializable {


     private long idconsejofacultad;
     private String nombre;
     private Date fechaCreacion;

    public ConsejoFacultad() {
    }

    public ConsejoFacultad(long idconsejofacultad, String nombre, Date fechaCreacion) {
       this.idconsejofacultad = idconsejofacultad;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
    }
   
     @Id 

    
    @Column(name="idconsejofacultad", unique=true, nullable=false)
    public long getIdconsejofacultad() {
        return this.idconsejofacultad;
    }
    
    public void setIdconsejofacultad(long idconsejofacultad) {
        this.idconsejofacultad = idconsejofacultad;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


