package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsejoUniversitario generated by hbm2java
 */
@Entity
@Table(name="ConsejoUniversitario"
    ,catalog="categorizacionbd"
)
public class ConsejoUniversitario  implements java.io.Serializable {


     private long idconsejouniversitario;
     private String nombre;
     private Date fechaCreacion;

    public ConsejoUniversitario() {
    }

    public ConsejoUniversitario(long idconsejouniversitario, String nombre, Date fechaCreacion) {
       this.idconsejouniversitario = idconsejouniversitario;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
    }
   
     @Id 

    
    @Column(name="idconsejouniversitario", unique=true, nullable=false)
    public long getIdconsejouniversitario() {
        return this.idconsejouniversitario;
    }
    
    public void setIdconsejouniversitario(long idconsejouniversitario) {
        this.idconsejouniversitario = idconsejouniversitario;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


