package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name="Docente"
    ,catalog="categorizacionbd"
)
public class Docente  implements java.io.Serializable {


     private long iddocente;
     private long idusuario;
     private String nombres;
     private String apepaterno;
     private String apematerno;
     private String nrodoc;
     private String cargo;

    public Docente() {
    }

	
    public Docente(long iddocente, long idusuario, String nombres, String apepaterno, String apematerno, String nrodoc) {
        this.iddocente = iddocente;
        this.idusuario = idusuario;
        this.nombres = nombres;
        this.apepaterno = apepaterno;
        this.apematerno = apematerno;
        this.nrodoc = nrodoc;
    }
    public Docente(long iddocente, long idusuario, String nombres, String apepaterno, String apematerno, String nrodoc, String cargo) {
       this.iddocente = iddocente;
       this.idusuario = idusuario;
       this.nombres = nombres;
       this.apepaterno = apepaterno;
       this.apematerno = apematerno;
       this.nrodoc = nrodoc;
       this.cargo = cargo;
    }
   
     @Id 

    
    @Column(name="iddocente", unique=true, nullable=false)
    public long getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(long iddocente) {
        this.iddocente = iddocente;
    }

    
    @Column(name="idusuario", nullable=false)
    public long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(long idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="nombres", nullable=false, length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apepaterno", nullable=false, length=50)
    public String getApepaterno() {
        return this.apepaterno;
    }
    
    public void setApepaterno(String apepaterno) {
        this.apepaterno = apepaterno;
    }

    
    @Column(name="apematerno", nullable=false, length=50)
    public String getApematerno() {
        return this.apematerno;
    }
    
    public void setApematerno(String apematerno) {
        this.apematerno = apematerno;
    }

    
    @Column(name="nrodoc", nullable=false, length=8)
    public String getNrodoc() {
        return this.nrodoc;
    }
    
    public void setNrodoc(String nrodoc) {
        this.nrodoc = nrodoc;
    }

    
    @Column(name="cargo", length=50)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }




}


