package pe.edu.unsch.entities;
// Generated Jun 14, 2019, 3:18:26 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Informe generated by hbm2java
 */
@Entity
@Table(name="Informe"
    ,catalog="categorizacionbd"
)
public class Informe  implements java.io.Serializable {


     private long idinforme;
     private Comision comision;
     private Promocion promocion;
     private TablaEv tablaEv;
     private String nombre;
     private Date fechaCreacion;
     private Set<InformeCf> informeCfs = new HashSet<InformeCf>(0);
     private Set<InformeCu> informeCus = new HashSet<InformeCu>(0);
     private Set<InformeDetalle> informeDetalles = new HashSet<InformeDetalle>(0);

    public Informe() {
    }

	
    public Informe(long idinforme, Comision comision, Promocion promocion, TablaEv tablaEv, String nombre, Date fechaCreacion) {
        this.idinforme = idinforme;
        this.comision = comision;
        this.promocion = promocion;
        this.tablaEv = tablaEv;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
    }
    public Informe(long idinforme, Comision comision, Promocion promocion, TablaEv tablaEv, String nombre, Date fechaCreacion, Set<InformeCf> informeCfs, Set<InformeCu> informeCus, Set<InformeDetalle> informeDetalles) {
       this.idinforme = idinforme;
       this.comision = comision;
       this.promocion = promocion;
       this.tablaEv = tablaEv;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.informeCfs = informeCfs;
       this.informeCus = informeCus;
       this.informeDetalles = informeDetalles;
    }
   
     @Id 

    
    @Column(name="idinforme", unique=true, nullable=false)
    public long getIdinforme() {
        return this.idinforme;
    }
    
    public void setIdinforme(long idinforme) {
        this.idinforme = idinforme;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcomision", nullable=false)
    public Comision getComision() {
        return this.comision;
    }
    
    public void setComision(Comision comision) {
        this.comision = comision;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpromocion", nullable=false)
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtablaev", nullable=false)
    public TablaEv getTablaEv() {
        return this.tablaEv;
    }
    
    public void setTablaEv(TablaEv tablaEv) {
        this.tablaEv = tablaEv;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="informe")
    public Set<InformeCf> getInformeCfs() {
        return this.informeCfs;
    }
    
    public void setInformeCfs(Set<InformeCf> informeCfs) {
        this.informeCfs = informeCfs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="informe")
    public Set<InformeCu> getInformeCus() {
        return this.informeCus;
    }
    
    public void setInformeCus(Set<InformeCu> informeCus) {
        this.informeCus = informeCus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="informe")
    public Set<InformeDetalle> getInformeDetalles() {
        return this.informeDetalles;
    }
    
    public void setInformeDetalles(Set<InformeDetalle> informeDetalles) {
        this.informeDetalles = informeDetalles;
    }




}


