package pe.edu.unsch.entities;
// Generated Jul 21, 2019, 9:48:04 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InformeCu generated by hbm2java
 */
@Entity
@Table(name="InformeCU"
    ,catalog="categorizacionbd"
)
public class InformeCu  implements java.io.Serializable {


     private Long idinformecu;
     private ConsejoUniversitario consejoUniversitario;
     private Informe informe;
     private boolean aprobado;
     private String detalle;

    public InformeCu() {
    }

    public InformeCu(ConsejoUniversitario consejoUniversitario, Informe informe, boolean aprobado, String detalle) {
       this.consejoUniversitario = consejoUniversitario;
       this.informe = informe;
       this.aprobado = aprobado;
       this.detalle = detalle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinformecu", unique=true, nullable=false)
    public Long getIdinformecu() {
        return this.idinformecu;
    }
    
    public void setIdinformecu(Long idinformecu) {
        this.idinformecu = idinformecu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idconsejouniversitario", nullable=false)
    public ConsejoUniversitario getConsejoUniversitario() {
        return this.consejoUniversitario;
    }
    
    public void setConsejoUniversitario(ConsejoUniversitario consejoUniversitario) {
        this.consejoUniversitario = consejoUniversitario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idinforme", nullable=false)
    public Informe getInforme() {
        return this.informe;
    }
    
    public void setInforme(Informe informe) {
        this.informe = informe;
    }

    
    @Column(name="aprobado", nullable=false)
    public boolean isAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(boolean aprobado) {
        this.aprobado = aprobado;
    }

    
    @Column(name="detalle", nullable=false, length=65535)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


