package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 3:58:00 PM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InformeCf generated by hbm2java
 */
@Entity
@Table(name="InformeCF"
    ,catalog="categorizacionbd"
)
public class InformeCf  implements java.io.Serializable {


     private Long idinformecf;
     private ConsejoFacultad consejoFacultad;
     private Informe informe;
     private boolean aprobado;
     private String detalle;

    public InformeCf() {
    }

    public InformeCf(ConsejoFacultad consejoFacultad, Informe informe, boolean aprobado, String detalle) {
       this.consejoFacultad = consejoFacultad;
       this.informe = informe;
       this.aprobado = aprobado;
       this.detalle = detalle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinformecf", unique=true, nullable=false)
    public Long getIdinformecf() {
        return this.idinformecf;
    }
    
    public void setIdinformecf(Long idinformecf) {
        this.idinformecf = idinformecf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idconsejofacultad", nullable=false)
    public ConsejoFacultad getConsejoFacultad() {
        return this.consejoFacultad;
    }
    
    public void setConsejoFacultad(ConsejoFacultad consejoFacultad) {
        this.consejoFacultad = consejoFacultad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idinforme", nullable=false)
    public Informe getInforme() {
        return this.informe;
    }
    
    public void setInforme(Informe informe) {
        this.informe = informe;
    }

    
    @Column(name="aprobado", nullable=false)
    public boolean isAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(boolean aprobado) {
        this.aprobado = aprobado;
    }

    
    @Column(name="detalle", nullable=false, length=65535)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


