package pe.edu.unsch.hibernate;
// Generated Jun 14, 2019, 3:18:26 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JefeDepartamento generated by hbm2java
 */
@Entity
@Table(name="JefeDepartamento"
    ,catalog="test"
)
public class JefeDepartamento  implements java.io.Serializable {


     private long idjefedepartamento;
     private String nombres;
     private String apepaterno;
     private String apematerno;
     private String nrodoc;
     private Date fechaDesigno;
     private Set<Comision> comisions = new HashSet<Comision>(0);

    public JefeDepartamento() {
    }

	
    public JefeDepartamento(long idjefedepartamento, String nombres, String apepaterno, String apematerno, String nrodoc, Date fechaDesigno) {
        this.idjefedepartamento = idjefedepartamento;
        this.nombres = nombres;
        this.apepaterno = apepaterno;
        this.apematerno = apematerno;
        this.nrodoc = nrodoc;
        this.fechaDesigno = fechaDesigno;
    }
    public JefeDepartamento(long idjefedepartamento, String nombres, String apepaterno, String apematerno, String nrodoc, Date fechaDesigno, Set<Comision> comisions) {
       this.idjefedepartamento = idjefedepartamento;
       this.nombres = nombres;
       this.apepaterno = apepaterno;
       this.apematerno = apematerno;
       this.nrodoc = nrodoc;
       this.fechaDesigno = fechaDesigno;
       this.comisions = comisions;
    }
   
     @Id 

    
    @Column(name="idjefedepartamento", unique=true, nullable=false)
    public long getIdjefedepartamento() {
        return this.idjefedepartamento;
    }
    
    public void setIdjefedepartamento(long idjefedepartamento) {
        this.idjefedepartamento = idjefedepartamento;
    }

    
    @Column(name="nombres", nullable=false, length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apepaterno", nullable=false, length=50)
    public String getApepaterno() {
        return this.apepaterno;
    }
    
    public void setApepaterno(String apepaterno) {
        this.apepaterno = apepaterno;
    }

    
    @Column(name="apematerno", nullable=false, length=50)
    public String getApematerno() {
        return this.apematerno;
    }
    
    public void setApematerno(String apematerno) {
        this.apematerno = apematerno;
    }

    
    @Column(name="nrodoc", nullable=false, length=8)
    public String getNrodoc() {
        return this.nrodoc;
    }
    
    public void setNrodoc(String nrodoc) {
        this.nrodoc = nrodoc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_designo", nullable=false, length=19)
    public Date getFechaDesigno() {
        return this.fechaDesigno;
    }
    
    public void setFechaDesigno(Date fechaDesigno) {
        this.fechaDesigno = fechaDesigno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jefeDepartamento")
    public Set<Comision> getComisions() {
        return this.comisions;
    }
    
    public void setComisions(Set<Comision> comisions) {
        this.comisions = comisions;
    }




}


