package pe.edu.unsch.entities;
// Generated Jul 21, 2019, 9:48:04 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JefeDepartamento generated by hbm2java
 */
@Entity
@Table(name="JefeDepartamento"
    ,catalog="categorizacionbd"
)
public class JefeDepartamento  implements java.io.Serializable {


     private Long idjefedepartamento;
     private Usuario usuario;
     private String nombres;
     private String apepaterno;
     private String apematerno;
     private String nrodoc;
     private String domicilio;
     private String celular;
     private String sexo;
     private Date fechaDesigno;
     private Date fechaNacimiento;
     private Set<Comision> comisions = new HashSet<Comision>(0);

    public JefeDepartamento() {
    }

	
    public JefeDepartamento(Usuario usuario, String nombres, String apepaterno, String apematerno, String nrodoc, Date fechaDesigno, Date fechaNacimiento) {
        this.usuario = usuario;
        this.nombres = nombres;
        this.apepaterno = apepaterno;
        this.apematerno = apematerno;
        this.nrodoc = nrodoc;
        this.fechaDesigno = fechaDesigno;
        this.fechaNacimiento = fechaNacimiento;
    }
    public JefeDepartamento(Usuario usuario, String nombres, String apepaterno, String apematerno, String nrodoc, String domicilio, String celular, String sexo, Date fechaDesigno, Date fechaNacimiento, Set<Comision> comisions) {
       this.usuario = usuario;
       this.nombres = nombres;
       this.apepaterno = apepaterno;
       this.apematerno = apematerno;
       this.nrodoc = nrodoc;
       this.domicilio = domicilio;
       this.celular = celular;
       this.sexo = sexo;
       this.fechaDesigno = fechaDesigno;
       this.fechaNacimiento = fechaNacimiento;
       this.comisions = comisions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idjefedepartamento", unique=true, nullable=false)
    public Long getIdjefedepartamento() {
        return this.idjefedepartamento;
    }
    
    public void setIdjefedepartamento(Long idjefedepartamento) {
        this.idjefedepartamento = idjefedepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombres", nullable=false, length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apepaterno", nullable=false, length=50)
    public String getApepaterno() {
        return this.apepaterno;
    }
    
    public void setApepaterno(String apepaterno) {
        this.apepaterno = apepaterno;
    }

    
    @Column(name="apematerno", nullable=false, length=50)
    public String getApematerno() {
        return this.apematerno;
    }
    
    public void setApematerno(String apematerno) {
        this.apematerno = apematerno;
    }

    
    @Column(name="nrodoc", nullable=false, length=8)
    public String getNrodoc() {
        return this.nrodoc;
    }
    
    public void setNrodoc(String nrodoc) {
        this.nrodoc = nrodoc;
    }

    
    @Column(name="domicilio", length=100)
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    
    @Column(name="celular", length=9)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_designo", nullable=false, length=19)
    public Date getFechaDesigno() {
        return this.fechaDesigno;
    }
    
    public void setFechaDesigno(Date fechaDesigno) {
        this.fechaDesigno = fechaDesigno;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_nacimiento", nullable=false, length=19)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jefeDepartamento")
    public Set<Comision> getComisions() {
        return this.comisions;
    }
    
    public void setComisions(Set<Comision> comisions) {
        this.comisions = comisions;
    }




}


