package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JefeDepartamento generated by hbm2java
 */
@Entity
@Table(name="JefeDepartamento"
    ,catalog="categorizacionbd"
)
public class JefeDepartamento  implements java.io.Serializable {


     private long idjefedepartamento;
     private long idusuario;
     private String nombres;
     private String apepaterno;
     private String apematerno;
     private String nrodoc;
     private Date fechaDesigno;

    public JefeDepartamento() {
    }

    public JefeDepartamento(long idjefedepartamento, long idusuario, String nombres, String apepaterno, String apematerno, String nrodoc, Date fechaDesigno) {
       this.idjefedepartamento = idjefedepartamento;
       this.idusuario = idusuario;
       this.nombres = nombres;
       this.apepaterno = apepaterno;
       this.apematerno = apematerno;
       this.nrodoc = nrodoc;
       this.fechaDesigno = fechaDesigno;
    }
   
     @Id 

    
    @Column(name="idjefedepartamento", unique=true, nullable=false)
    public long getIdjefedepartamento() {
        return this.idjefedepartamento;
    }
    
    public void setIdjefedepartamento(long idjefedepartamento) {
        this.idjefedepartamento = idjefedepartamento;
    }

    
    @Column(name="idusuario", nullable=false)
    public long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(long idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="nombres", nullable=false, length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apepaterno", nullable=false, length=50)
    public String getApepaterno() {
        return this.apepaterno;
    }
    
    public void setApepaterno(String apepaterno) {
        this.apepaterno = apepaterno;
    }

    
    @Column(name="apematerno", nullable=false, length=50)
    public String getApematerno() {
        return this.apematerno;
    }
    
    public void setApematerno(String apematerno) {
        this.apematerno = apematerno;
    }

    
    @Column(name="nrodoc", nullable=false, length=8)
    public String getNrodoc() {
        return this.nrodoc;
    }
    
    public void setNrodoc(String nrodoc) {
        this.nrodoc = nrodoc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_designo", nullable=false, length=19)
    public Date getFechaDesigno() {
        return this.fechaDesigno;
    }
    
    public void setFechaDesigno(Date fechaDesigno) {
        this.fechaDesigno = fechaDesigno;
    }




}


