package pe.edu.unsch.entities;
// Generated Jul 21, 2019, 9:48:04 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="Perfil"
    ,catalog="categorizacionbd"
)
public class Perfil  implements java.io.Serializable {


     private Long idperfil;
     private String nombre;
     private Set<UsuarioPerfil> usuarioPerfils = new HashSet<UsuarioPerfil>(0);

    public Perfil() {
    }

	
    public Perfil(String nombre) {
        this.nombre = nombre;
    }
    public Perfil(String nombre, Set<UsuarioPerfil> usuarioPerfils) {
       this.nombre = nombre;
       this.usuarioPerfils = usuarioPerfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idperfil", unique=true, nullable=false)
    public Long getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(Long idperfil) {
        this.idperfil = idperfil;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perfil")
    public Set<UsuarioPerfil> getUsuarioPerfils() {
        return this.usuarioPerfils;
    }
    
    public void setUsuarioPerfils(Set<UsuarioPerfil> usuarioPerfils) {
        this.usuarioPerfils = usuarioPerfils;
    }




}


