package pe.edu.unsch.entities;
// Generated Jul 23, 2019, 11:26:04 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;

import java.util.HashSet;

import java.util.Set;

import javax.persistence.Column;

import javax.persistence.Entity;

import javax.persistence.FetchType;

import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;

import javax.persistence.JoinColumn;

import javax.persistence.ManyToOne;

import javax.persistence.OneToMany;

import javax.persistence.Table;

import javax.persistence.Temporal;

import javax.persistence.TemporalType;


/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="Promocion"
    ,catalog="categorizacionbd"
)
public class Promocion  implements java.io.Serializable {


     private Long idpromocion;
     private Categoria categoria;
     private Docente docente;
     private Expediente expediente;
     private Date fechaSolicitud;
     private Set<Informe> informes = new HashSet<Informe>(0);

    public Promocion() {
    }

	
    public Promocion(Categoria categoria, Docente docente, Expediente expediente, Date fechaSolicitud) {
        this.categoria = categoria;
        this.docente = docente;
        this.expediente = expediente;
        this.fechaSolicitud = fechaSolicitud;
    }
    public Promocion(Categoria categoria, Docente docente, Expediente expediente, Date fechaSolicitud, Set<Informe> informes) {
       this.categoria = categoria;
       this.docente = docente;
       this.expediente = expediente;
       this.fechaSolicitud = fechaSolicitud;
       this.informes = informes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpromocion", unique=true, nullable=false)
    public Long getIdpromocion() {
        return this.idpromocion;
    }
    
    public void setIdpromocion(Long idpromocion) {
        this.idpromocion = idpromocion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddocente", nullable=false)
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idexpediente", nullable=false)
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_solicitud", nullable=false, length=19)
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="promocion")
    public Set<Informe> getInformes() {
        return this.informes;
    }
    
    public void setInformes(Set<Informe> informes) {
        this.informes = informes;
    }




}

