package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="Promocion"
    ,catalog="categorizacionbd"
)
public class Promocion  implements java.io.Serializable {


     private long idpromocion;
     private long iddocente;
     private long idcategoria;
     private String solicitud;
     private String expediente;
     private Date fechaSolicitud;

    public Promocion() {
    }

    public Promocion(long idpromocion, long iddocente, long idcategoria, String solicitud, String expediente, Date fechaSolicitud) {
       this.idpromocion = idpromocion;
       this.iddocente = iddocente;
       this.idcategoria = idcategoria;
       this.solicitud = solicitud;
       this.expediente = expediente;
       this.fechaSolicitud = fechaSolicitud;
    }
   
     @Id 

    
    @Column(name="idpromocion", unique=true, nullable=false)
    public long getIdpromocion() {
        return this.idpromocion;
    }
    
    public void setIdpromocion(long idpromocion) {
        this.idpromocion = idpromocion;
    }

    
    @Column(name="iddocente", nullable=false)
    public long getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(long iddocente) {
        this.iddocente = iddocente;
    }

    
    @Column(name="idcategoria", nullable=false)
    public long getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(long idcategoria) {
        this.idcategoria = idcategoria;
    }

    
    @Column(name="solicitud", nullable=false, length=50)
    public String getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(String solicitud) {
        this.solicitud = solicitud;
    }

    
    @Column(name="expediente", nullable=false, length=50)
    public String getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(String expediente) {
        this.expediente = expediente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_solicitud", nullable=false, length=19)
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }




}


