package pe.edu.unsch.hibernate;
// Generated Jun 14, 2019, 3:18:26 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="Promocion"
    ,catalog="test"
)
public class Promocion  implements java.io.Serializable {


     private long idpromocion;
     private Categoria categoria;
     private Docente docente;
     private String solicitud;
     private String expediente;
     private Date fechaSolicitud;
     private Set<Informe> informes = new HashSet<Informe>(0);

    public Promocion() {
    }

	
    public Promocion(long idpromocion, Categoria categoria, Docente docente, String solicitud, String expediente, Date fechaSolicitud) {
        this.idpromocion = idpromocion;
        this.categoria = categoria;
        this.docente = docente;
        this.solicitud = solicitud;
        this.expediente = expediente;
        this.fechaSolicitud = fechaSolicitud;
    }
    public Promocion(long idpromocion, Categoria categoria, Docente docente, String solicitud, String expediente, Date fechaSolicitud, Set<Informe> informes) {
       this.idpromocion = idpromocion;
       this.categoria = categoria;
       this.docente = docente;
       this.solicitud = solicitud;
       this.expediente = expediente;
       this.fechaSolicitud = fechaSolicitud;
       this.informes = informes;
    }
   
     @Id 

    
    @Column(name="idpromocion", unique=true, nullable=false)
    public long getIdpromocion() {
        return this.idpromocion;
    }
    
    public void setIdpromocion(long idpromocion) {
        this.idpromocion = idpromocion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddocente", nullable=false)
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    
    @Column(name="solicitud", nullable=false, length=50)
    public String getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(String solicitud) {
        this.solicitud = solicitud;
    }

    
    @Column(name="expediente", nullable=false, length=50)
    public String getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(String expediente) {
        this.expediente = expediente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_solicitud", nullable=false, length=19)
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="promocion")
    public Set<Informe> getInformes() {
        return this.informes;
    }
    
    public void setInformes(Set<Informe> informes) {
        this.informes = informes;
    }




}


