package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resolucion generated by hbm2java
 */
@Entity
@Table(name="Resolucion"
    ,catalog="categorizacionbd"
)
public class Resolucion  implements java.io.Serializable {


     private long idresolucion;
     private String nro;
     private String resumen;
     private String contenido;
     private Long idconsejouniversitario;

    public Resolucion() {
    }

	
    public Resolucion(long idresolucion, String nro, String resumen, String contenido) {
        this.idresolucion = idresolucion;
        this.nro = nro;
        this.resumen = resumen;
        this.contenido = contenido;
    }
    public Resolucion(long idresolucion, String nro, String resumen, String contenido, Long idconsejouniversitario) {
       this.idresolucion = idresolucion;
       this.nro = nro;
       this.resumen = resumen;
       this.contenido = contenido;
       this.idconsejouniversitario = idconsejouniversitario;
    }
   
     @Id 

    
    @Column(name="idresolucion", unique=true, nullable=false)
    public long getIdresolucion() {
        return this.idresolucion;
    }
    
    public void setIdresolucion(long idresolucion) {
        this.idresolucion = idresolucion;
    }

    
    @Column(name="nro", nullable=false, length=50)
    public String getNro() {
        return this.nro;
    }
    
    public void setNro(String nro) {
        this.nro = nro;
    }

    
    @Column(name="resumen", nullable=false, length=50)
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    
    @Column(name="contenido", nullable=false, length=65535)
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    
    @Column(name="idconsejouniversitario")
    public Long getIdconsejouniversitario() {
        return this.idconsejouniversitario;
    }
    
    public void setIdconsejouniversitario(Long idconsejouniversitario) {
        this.idconsejouniversitario = idconsejouniversitario;
    }




}


