package pe.edu.unsch.entities;
// Generated Jun 28, 2019, 3:58:00 PM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resolucion generated by hbm2java
 */
@Entity
@Table(name="Resolucion"
    ,catalog="categorizacionbd"
)
public class Resolucion  implements java.io.Serializable {


     private Long idresolucion;
     private ConsejoUniversitario consejoUniversitario;
     private String nro;
     private String resumen;
     private String contenido;

    public Resolucion() {
    }

	
    public Resolucion(String nro, String resumen, String contenido) {
        this.nro = nro;
        this.resumen = resumen;
        this.contenido = contenido;
    }
    public Resolucion(ConsejoUniversitario consejoUniversitario, String nro, String resumen, String contenido) {
       this.consejoUniversitario = consejoUniversitario;
       this.nro = nro;
       this.resumen = resumen;
       this.contenido = contenido;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idresolucion", unique=true, nullable=false)
    public Long getIdresolucion() {
        return this.idresolucion;
    }
    
    public void setIdresolucion(Long idresolucion) {
        this.idresolucion = idresolucion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idconsejouniversitario")
    public ConsejoUniversitario getConsejoUniversitario() {
        return this.consejoUniversitario;
    }
    
    public void setConsejoUniversitario(ConsejoUniversitario consejoUniversitario) {
        this.consejoUniversitario = consejoUniversitario;
    }

    
    @Column(name="nro", nullable=false, length=50)
    public String getNro() {
        return this.nro;
    }
    
    public void setNro(String nro) {
        this.nro = nro;
    }

    
    @Column(name="resumen", nullable=false, length=50)
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    
    @Column(name="contenido", nullable=false, length=65535)
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


