package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 10:54:14 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TablaEvDetalle generated by hbm2java
 */
@Entity
@Table(name="TablaEvDetalle"
    ,catalog="categorizacionbd"
)
public class TablaEvDetalle  implements java.io.Serializable {


     private long idtablaevdetalle;
     private TablaEv tablaEv;
     private String indicador;
     private String descripcion;
     private short puntaje;
     private Set<InformeDetalle> informeDetalles = new HashSet<InformeDetalle>(0);

    public TablaEvDetalle() {
    }

	
    public TablaEvDetalle(long idtablaevdetalle, TablaEv tablaEv, String indicador, String descripcion, short puntaje) {
        this.idtablaevdetalle = idtablaevdetalle;
        this.tablaEv = tablaEv;
        this.indicador = indicador;
        this.descripcion = descripcion;
        this.puntaje = puntaje;
    }
    public TablaEvDetalle(long idtablaevdetalle, TablaEv tablaEv, String indicador, String descripcion, short puntaje, Set<InformeDetalle> informeDetalles) {
       this.idtablaevdetalle = idtablaevdetalle;
       this.tablaEv = tablaEv;
       this.indicador = indicador;
       this.descripcion = descripcion;
       this.puntaje = puntaje;
       this.informeDetalles = informeDetalles;
    }
   
     @Id 

    
    @Column(name="idtablaevdetalle", unique=true, nullable=false)
    public long getIdtablaevdetalle() {
        return this.idtablaevdetalle;
    }
    
    public void setIdtablaevdetalle(long idtablaevdetalle) {
        this.idtablaevdetalle = idtablaevdetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtablaev", nullable=false)
    public TablaEv getTablaEv() {
        return this.tablaEv;
    }
    
    public void setTablaEv(TablaEv tablaEv) {
        this.tablaEv = tablaEv;
    }

    
    @Column(name="indicador", nullable=false, length=50)
    public String getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(String indicador) {
        this.indicador = indicador;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="puntaje", nullable=false)
    public short getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(short puntaje) {
        this.puntaje = puntaje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tablaEvDetalle")
    public Set<InformeDetalle> getInformeDetalles() {
        return this.informeDetalles;
    }
    
    public void setInformeDetalles(Set<InformeDetalle> informeDetalles) {
        this.informeDetalles = informeDetalles;
    }




}


