package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TablaEv generated by hbm2java
 */
@Entity
@Table(name="TablaEv"
    ,catalog="categorizacionbd"
)
public class TablaEv  implements java.io.Serializable {


     private long idtablaev;

    public TablaEv() {
    }

    public TablaEv(long idtablaev) {
       this.idtablaev = idtablaev;
    }
   
     @Id 

    
    @Column(name="idtablaev", unique=true, nullable=false)
    public long getIdtablaev() {
        return this.idtablaev;
    }
    
    public void setIdtablaev(long idtablaev) {
        this.idtablaev = idtablaev;
    }




}


