package pe.edu.unsch.hibernate;
// Generated Jun 28, 2019, 8:47:33 AM by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TablaEvDetalle generated by hbm2java
 */
@Entity
@Table(name="TablaEvDetalle"
    ,catalog="categorizacionbd"
)
public class TablaEvDetalle  implements java.io.Serializable {


     private long idtablaevdetalle;
     private long idtablaev;
     private String indicador;
     private String descripcion;
     private short puntaje;

    public TablaEvDetalle() {
    }

    public TablaEvDetalle(long idtablaevdetalle, long idtablaev, String indicador, String descripcion, short puntaje) {
       this.idtablaevdetalle = idtablaevdetalle;
       this.idtablaev = idtablaev;
       this.indicador = indicador;
       this.descripcion = descripcion;
       this.puntaje = puntaje;
    }
   
     @Id 

    
    @Column(name="idtablaevdetalle", unique=true, nullable=false)
    public long getIdtablaevdetalle() {
        return this.idtablaevdetalle;
    }
    
    public void setIdtablaevdetalle(long idtablaevdetalle) {
        this.idtablaevdetalle = idtablaevdetalle;
    }

    
    @Column(name="idtablaev", nullable=false)
    public long getIdtablaev() {
        return this.idtablaev;
    }
    
    public void setIdtablaev(long idtablaev) {
        this.idtablaev = idtablaev;
    }

    
    @Column(name="indicador", nullable=false, length=50)
    public String getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(String indicador) {
        this.indicador = indicador;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="puntaje", nullable=false)
    public short getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(short puntaje) {
        this.puntaje = puntaje;
    }




}


