package pe.edu.unsch.entities;
// Generated Jun 14, 2019, 5:09:22 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="Usuario"
    ,catalog="categorizacionbd"
)
public class Usuario  implements java.io.Serializable {


     private long idusuario;
     private String usuario;
     private String password;
     private String foto;
     private Set<Docente> docentes = new HashSet<Docente>(0);

    public Usuario() {
    }

	
    public Usuario(long idusuario, String usuario, String password) {
        this.idusuario = idusuario;
        this.usuario = usuario;
        this.password = password;
    }
    public Usuario(long idusuario, String usuario, String password, String foto, Set<Docente> docentes) {
       this.idusuario = idusuario;
       this.usuario = usuario;
       this.password = password;
       this.foto = foto;
       this.docentes = docentes;
    }
   
     @Id 

    
    @Column(name="idusuario", unique=true, nullable=false)
    public long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(long idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="usuario", nullable=false, length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="foto", length=100)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }




}


